/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConsumptionRouteImport } from './routes/consumption'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FutureRouteImport } from './routes/future'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as PauseRouteImport } from './routes/pause'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodayRouteImport } from './routes/today'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ElectronicsIndexRouteImport } from './routes/electronics.index'
import { Route as ElectronicsProductIdRouteImport } from './routes/electronics.$productId'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLessonIdRouteImport } from './routes/learn.$lessonId'
import { Route as FoodAppIdIndexRouteImport } from './routes/food.$appId.index'
import { Route as FoodAppIdRestaurantIdRouteImport } from './routes/food.$appId.$restaurantId'
import { Route as MarketVerticalIndexRouteImport } from './routes/market.$vertical.index'
import { Route as MarketVerticalProductIdRouteImport } from './routes/market.$vertical.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumptionRoute = ConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const PauseRoute = PauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicsIndexRoute = ElectronicsIndexRouteImport.update({
  id: '/electronics/',
  path: '/electronics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicsProductIdRoute = ElectronicsProductIdRouteImport.update({
  id: '/electronics/$productId',
  path: '/electronics/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/food/',
  path: '/food/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLessonIdRoute = LearnLessonIdRouteImport.update({
  id: '/learn/$lessonId',
  path: '/learn/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAppIdIndexRoute = FoodAppIdIndexRouteImport.update({
  id: '/food/$appId/',
  path: '/food/$appId/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAppIdRestaurantIdRoute = FoodAppIdRestaurantIdRouteImport.update({
  id: '/food/$appId/$restaurantId',
  path: '/food/$appId/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketVerticalIndexRoute = MarketVerticalIndexRouteImport.update({
  id: '/market/$vertical/',
  path: '/market/$vertical/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketVerticalProductIdRoute = MarketVerticalProductIdRouteImport.update({
  id: '/market/$vertical/$productId',
  path: '/market/$vertical/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consumption': typeof ConsumptionRoute
  '/continue': typeof ContinueRoute
  '/feedback': typeof FeedbackRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/pause': typeof PauseRoute
  '/profile': typeof ProfileRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/wishlist': typeof WishlistRoute
  '/electronics/$productId': typeof ElectronicsProductIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/electronics/': typeof ElectronicsIndexRoute
  '/food/': typeof FoodIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/food/$appId/$restaurantId': typeof FoodAppIdRestaurantIdRoute
  '/market/$vertical/$productId': typeof MarketVerticalProductIdRoute
  '/food/$appId/': typeof FoodAppIdIndexRoute
  '/market/$vertical/': typeof MarketVerticalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consumption': typeof ConsumptionRoute
  '/continue': typeof ContinueRoute
  '/feedback': typeof FeedbackRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/pause': typeof PauseRoute
  '/profile': typeof ProfileRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/wishlist': typeof WishlistRoute
  '/electronics/$productId': typeof ElectronicsProductIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/electronics': typeof ElectronicsIndexRoute
  '/food': typeof FoodIndexRoute
  '/learn': typeof LearnIndexRoute
  '/food/$appId/$restaurantId': typeof FoodAppIdRestaurantIdRoute
  '/market/$vertical/$productId': typeof MarketVerticalProductIdRoute
  '/food/$appId': typeof FoodAppIdIndexRoute
  '/market/$vertical': typeof MarketVerticalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consumption': typeof ConsumptionRoute
  '/continue': typeof ContinueRoute
  '/feedback': typeof FeedbackRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/pause': typeof PauseRoute
  '/profile': typeof ProfileRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/wishlist': typeof WishlistRoute
  '/electronics/$productId': typeof ElectronicsProductIdRoute
  '/learn/$lessonId': typeof LearnLessonIdRoute
  '/electronics/': typeof ElectronicsIndexRoute
  '/food/': typeof FoodIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/food/$appId/$restaurantId': typeof FoodAppIdRestaurantIdRoute
  '/market/$vertical/$productId': typeof MarketVerticalProductIdRoute
  '/food/$appId/': typeof FoodAppIdIndexRoute
  '/market/$vertical/': typeof MarketVerticalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/cart'
    | '/checkout'
    | '/consumption'
    | '/continue'
    | '/feedback'
    | '/future'
    | '/journey'
    | '/pause'
    | '/profile'
    | '/savings'
    | '/settings'
    | '/today'
    | '/wishlist'
    | '/electronics/$productId'
    | '/learn/$lessonId'
    | '/electronics/'
    | '/food/'
    | '/learn/'
    | '/food/$appId/$restaurantId'
    | '/market/$vertical/$productId'
    | '/food/$appId/'
    | '/market/$vertical/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/cart'
    | '/checkout'
    | '/consumption'
    | '/continue'
    | '/feedback'
    | '/future'
    | '/journey'
    | '/pause'
    | '/profile'
    | '/savings'
    | '/settings'
    | '/today'
    | '/wishlist'
    | '/electronics/$productId'
    | '/learn/$lessonId'
    | '/electronics'
    | '/food'
    | '/learn'
    | '/food/$appId/$restaurantId'
    | '/market/$vertical/$productId'
    | '/food/$appId'
    | '/market/$vertical'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/cart'
    | '/checkout'
    | '/consumption'
    | '/continue'
    | '/feedback'
    | '/future'
    | '/journey'
    | '/pause'
    | '/profile'
    | '/savings'
    | '/settings'
    | '/today'
    | '/wishlist'
    | '/electronics/$productId'
    | '/learn/$lessonId'
    | '/electronics/'
    | '/food/'
    | '/learn/'
    | '/food/$appId/$restaurantId'
    | '/market/$vertical/$productId'
    | '/food/$appId/'
    | '/market/$vertical/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConsumptionRoute: typeof ConsumptionRoute
  ContinueRoute: typeof ContinueRoute
  FeedbackRoute: typeof FeedbackRoute
  FutureRoute: typeof FutureRoute
  JourneyRoute: typeof JourneyRoute
  PauseRoute: typeof PauseRoute
  ProfileRoute: typeof ProfileRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  WishlistRoute: typeof WishlistRoute
  ElectronicsProductIdRoute: typeof ElectronicsProductIdRoute
  LearnLessonIdRoute: typeof LearnLessonIdRoute
  ElectronicsIndexRoute: typeof ElectronicsIndexRoute
  FoodIndexRoute: typeof FoodIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  FoodAppIdRestaurantIdRoute: typeof FoodAppIdRestaurantIdRoute
  MarketVerticalProductIdRoute: typeof MarketVerticalProductIdRoute
  FoodAppIdIndexRoute: typeof FoodAppIdIndexRoute
  MarketVerticalIndexRoute: typeof MarketVerticalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumption': {
      id: '/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof ConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pause': {
      id: '/pause'
      path: '/pause'
      fullPath: '/pause'
      preLoaderRoute: typeof PauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronics/': {
      id: '/electronics/'
      path: '/electronics'
      fullPath: '/electronics/'
      preLoaderRoute: typeof ElectronicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronics/$productId': {
      id: '/electronics/$productId'
      path: '/electronics/$productId'
      fullPath: '/electronics/$productId'
      preLoaderRoute: typeof ElectronicsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/': {
      id: '/food/'
      path: '/food'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$lessonId': {
      id: '/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof LearnLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$appId/': {
      id: '/food/$appId/'
      path: '/food/$appId'
      fullPath: '/food/$appId/'
      preLoaderRoute: typeof FoodAppIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$appId/$restaurantId': {
      id: '/food/$appId/$restaurantId'
      path: '/food/$appId/$restaurantId'
      fullPath: '/food/$appId/$restaurantId'
      preLoaderRoute: typeof FoodAppIdRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$vertical/': {
      id: '/market/$vertical/'
      path: '/market/$vertical'
      fullPath: '/market/$vertical/'
      preLoaderRoute: typeof MarketVerticalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$vertical/$productId': {
      id: '/market/$vertical/$productId'
      path: '/market/$vertical/$productId'
      fullPath: '/market/$vertical/$productId'
      preLoaderRoute: typeof MarketVerticalProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConsumptionRoute: ConsumptionRoute,
  ContinueRoute: ContinueRoute,
  FeedbackRoute: FeedbackRoute,
  FutureRoute: FutureRoute,
  JourneyRoute: JourneyRoute,
  PauseRoute: PauseRoute,
  ProfileRoute: ProfileRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  WishlistRoute: WishlistRoute,
  ElectronicsProductIdRoute: ElectronicsProductIdRoute,
  LearnLessonIdRoute: LearnLessonIdRoute,
  ElectronicsIndexRoute: ElectronicsIndexRoute,
  FoodIndexRoute: FoodIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  FoodAppIdRestaurantIdRoute: FoodAppIdRestaurantIdRoute,
  MarketVerticalProductIdRoute: MarketVerticalProductIdRoute,
  FoodAppIdIndexRoute: FoodAppIdIndexRoute,
  MarketVerticalIndexRoute: MarketVerticalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
