/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrderRouteImport } from './routes/order'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as FutureRouteImport } from './routes/future'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/continue': typeof ContinueRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/restaurant': typeof RestaurantRoute
  '/restaurants': typeof RestaurantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/continue': typeof ContinueRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/restaurant': typeof RestaurantRoute
  '/restaurants': typeof RestaurantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/continue': typeof ContinueRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/restaurant': typeof RestaurantRoute
  '/restaurants': typeof RestaurantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/continue'
    | '/future'
    | '/journey'
    | '/order'
    | '/profile'
    | '/restaurant'
    | '/restaurants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/continue'
    | '/future'
    | '/journey'
    | '/order'
    | '/profile'
    | '/restaurant'
    | '/restaurants'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/continue'
    | '/future'
    | '/journey'
    | '/order'
    | '/profile'
    | '/restaurant'
    | '/restaurants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ContinueRoute: typeof ContinueRoute
  FutureRoute: typeof FutureRoute
  JourneyRoute: typeof JourneyRoute
  OrderRoute: typeof OrderRoute
  ProfileRoute: typeof ProfileRoute
  RestaurantRoute: typeof RestaurantRoute
  RestaurantsRoute: typeof RestaurantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ContinueRoute: ContinueRoute,
  FutureRoute: FutureRoute,
  JourneyRoute: JourneyRoute,
  OrderRoute: OrderRoute,
  ProfileRoute: ProfileRoute,
  RestaurantRoute: RestaurantRoute,
  RestaurantsRoute: RestaurantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
