/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as FutureRouteImport } from './routes/future'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as PauseRouteImport } from './routes/pause'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TodayRouteImport } from './routes/today'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as FoodAppIdIndexRouteImport } from './routes/food.$appId.index'
import { Route as FoodAppIdRestaurantIdRouteImport } from './routes/food.$appId.$restaurantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureRoute = FutureRouteImport.update({
  id: '/future',
  path: '/future',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const PauseRoute = PauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/food/',
  path: '/food/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAppIdIndexRoute = FoodAppIdIndexRouteImport.update({
  id: '/food/$appId/',
  path: '/food/$appId/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAppIdRestaurantIdRoute = FoodAppIdRestaurantIdRouteImport.update({
  id: '/food/$appId/$restaurantId',
  path: '/food/$appId/$restaurantId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/continue': typeof ContinueRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/pause': typeof PauseRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
  '/food/': typeof FoodIndexRoute
  '/food/$appId/$restaurantId': typeof FoodAppIdRestaurantIdRoute
  '/food/$appId/': typeof FoodAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/continue': typeof ContinueRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/pause': typeof PauseRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
  '/food': typeof FoodIndexRoute
  '/food/$appId/$restaurantId': typeof FoodAppIdRestaurantIdRoute
  '/food/$appId': typeof FoodAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/continue': typeof ContinueRoute
  '/future': typeof FutureRoute
  '/journey': typeof JourneyRoute
  '/pause': typeof PauseRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
  '/food/': typeof FoodIndexRoute
  '/food/$appId/$restaurantId': typeof FoodAppIdRestaurantIdRoute
  '/food/$appId/': typeof FoodAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/cart'
    | '/checkout'
    | '/continue'
    | '/future'
    | '/journey'
    | '/pause'
    | '/profile'
    | '/today'
    | '/food/'
    | '/food/$appId/$restaurantId'
    | '/food/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/cart'
    | '/checkout'
    | '/continue'
    | '/future'
    | '/journey'
    | '/pause'
    | '/profile'
    | '/today'
    | '/food'
    | '/food/$appId/$restaurantId'
    | '/food/$appId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/cart'
    | '/checkout'
    | '/continue'
    | '/future'
    | '/journey'
    | '/pause'
    | '/profile'
    | '/today'
    | '/food/'
    | '/food/$appId/$restaurantId'
    | '/food/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContinueRoute: typeof ContinueRoute
  FutureRoute: typeof FutureRoute
  JourneyRoute: typeof JourneyRoute
  PauseRoute: typeof PauseRoute
  ProfileRoute: typeof ProfileRoute
  TodayRoute: typeof TodayRoute
  FoodIndexRoute: typeof FoodIndexRoute
  FoodAppIdRestaurantIdRoute: typeof FoodAppIdRestaurantIdRoute
  FoodAppIdIndexRoute: typeof FoodAppIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future': {
      id: '/future'
      path: '/future'
      fullPath: '/future'
      preLoaderRoute: typeof FutureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pause': {
      id: '/pause'
      path: '/pause'
      fullPath: '/pause'
      preLoaderRoute: typeof PauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/': {
      id: '/food/'
      path: '/food'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$appId/': {
      id: '/food/$appId/'
      path: '/food/$appId'
      fullPath: '/food/$appId/'
      preLoaderRoute: typeof FoodAppIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$appId/$restaurantId': {
      id: '/food/$appId/$restaurantId'
      path: '/food/$appId/$restaurantId'
      fullPath: '/food/$appId/$restaurantId'
      preLoaderRoute: typeof FoodAppIdRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContinueRoute: ContinueRoute,
  FutureRoute: FutureRoute,
  JourneyRoute: JourneyRoute,
  PauseRoute: PauseRoute,
  ProfileRoute: ProfileRoute,
  TodayRoute: TodayRoute,
  FoodIndexRoute: FoodIndexRoute,
  FoodAppIdRestaurantIdRoute: FoodAppIdRestaurantIdRoute,
  FoodAppIdIndexRoute: FoodAppIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
