// Automated image-production pipeline for the LAUNCH VISUAL CATALOGUE (34 products).
//
// Requires a Pexels API key (licensed, commercial use allowed; attribution kept):
//   PEXELS_API_KEY=xxxxx node scripts/fetch-pexels.mjs            # launch set
//   PEXELS_API_KEY=xxxxx node scripts/fetch-pexels.mjs --all      # whole catalogue
//
// It: reads docs/product-image-manifest.json → derives a query per product →
// downloads the best landscape photo to public/products/<folder>/<id>.jpg →
// writes src/lib/photoRegistry.generated.ts (with photographer credit + license).
// Then run `node scripts/image-audit.mjs` to verify. No keys are committed; the
// frontend never sees the key (this is a build-time script).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const KEY = process.env.PEXELS_API_KEY;
if (!KEY) {
  console.error("Missing PEXELS_API_KEY. Get one at https://www.pexels.com/api/ and re-run:\n  PEXELS_API_KEY=xxx node scripts/fetch-pexels.mjs");
  process.exit(2);
}
const ALL = process.argv.includes("--all");
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(join(root, "..", "docs", "product-image-manifest.json"), "utf8"));

// Query hints keep results on-brief (generic, India-first where it matters).
const HINT = {
  electronics: "product studio white background",
  shopping: "clothing product studio",
  grocery: "grocery product packaging",
  beauty: "cosmetic bottle product studio",
  home: "home product studio",
  travel: "india travel",
  entertainment: "entertainment",
  food: "indian food dish",
};
const q = (it) => `${it.name} ${HINT[it.vertical] ?? "product"}`.replace(/\([^)]*\)/g, "").trim();

async function pexels(query) {
  const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=3&orientation=landscape`;
  const r = await fetch(url, { headers: { Authorization: KEY } });
  if (!r.ok) throw new Error(`Pexels ${r.status} for "${query}"`);
  const j = await r.json();
  return j.photos?.[0];
}

async function download(src, dest) {
  const r = await fetch(src);
  if (!r.ok) throw new Error(`download ${r.status}`);
  const buf = Buffer.from(await r.arrayBuffer());
  writeFileSync(dest, buf);
}

const targets = manifest.products.filter((p) => ALL || p.launch);
console.log(`Fetching ${targets.length} images from Pexels…`);
const registry = {};
let ok = 0;
for (const it of targets) {
  try {
    const photo = await pexels(q(it));
    if (!photo) { console.log(`  · no result: ${it.productId} ("${q(it)}")`); continue; }
    const folder = it.photoFilename.split("/")[0];
    mkdirSync(join(root, "public", "products", folder), { recursive: true });
    const rel = `products/${folder}/${it.productId}.jpg`;
    await download(photo.src.large2x || photo.src.large, join(root, "public", rel));
    registry[it.productId] = {
      type: "remote-cached-local",
      src: `/${rel}`,
      credit: `Photo by ${photo.photographer} on Pexels`,
      source: "pexels",
      sourceId: String(photo.id),
      licenseNote: "Pexels License (free for commercial use; attribution appreciated)",
    };
    ok++;
    console.log(`  ✓ ${it.productId}`);
    await new Promise((r) => setTimeout(r, 250)); // be polite to the API
  } catch (e) {
    console.log(`  ✗ ${it.productId}: ${e.message}`);
  }
}

// Emit the generated registry (type stored as "local" since files are committed).
const entries = Object.entries(registry)
  .map(([id, m]) => `  ${JSON.stringify(id)}: { type: "local", src: ${JSON.stringify(m.src)}, credit: ${JSON.stringify(m.credit)}, source: "pexels", sourceId: ${JSON.stringify(m.sourceId)}, licenseNote: ${JSON.stringify(m.licenseNote)} },`)
  .join("\n");
const out = `// AUTO-GENERATED by scripts/fetch-pexels.mjs. Do not edit by hand.
import type { ProductMedia } from "./productImages";

export const GENERATED_PHOTOS: Record<string, ProductMedia> = {
${entries}
};
`;
writeFileSync(join(root, "src", "lib", "photoRegistry.generated.ts"), out);
console.log(`\nDone: ${ok}/${targets.length} images saved + registered.`);
console.log("Next: node scripts/image-audit.mjs  (then build & deploy)");
