// Scan public/products/<folder>/ for real image files that match catalogue product
// ids and (re)write src/lib/photoRegistry.generated.ts so they appear everywhere.
// Run after dropping images in:  node scripts/register-local.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(join(root, "..", "docs", "product-image-manifest.json"), "utf8"));
const EXTS = ["webp", "jpg", "jpeg", "avif", "png"];

const found = {};
for (const p of manifest.products) {
  const folder = p.photoFilename.split("/")[0];
  for (const e of EXTS) {
    const rel = `products/${folder}/${p.productId}.${e}`;
    if (existsSync(join(root, "public", rel))) { found[p.productId] = `/${rel}`; break; }
  }
}

const entries = Object.entries(found)
  .map(([id, src]) => `  ${JSON.stringify(id)}: { type: "local", src: ${JSON.stringify(src)} },`)
  .join("\n");
const out = `// AUTO-GENERATED by scripts/register-local.mjs. Do not edit by hand.
import type { ProductMedia } from "./productImages";

export const GENERATED_PHOTOS: Record<string, ProductMedia> = {
${entries}
};
`;
writeFileSync(join(root, "src", "lib", "photoRegistry.generated.ts"), out);
console.log(`Registered ${Object.keys(found).length} local product photo(s).`);
if (Object.keys(found).length) console.log(Object.keys(found).join(", "));
console.log("Next: node scripts/image-audit.mjs  (then build & deploy)");
