import { Link } from "react-router-dom";

/**
 * Public privacy policy page — hosted at /privacy so it can be linked from
 * the Google Play Console (Play requires a public privacy-policy URL).
 * Content mirrors docs/privacy-policy.md. Keep the two in sync.
 */
function Privacy() {
  return (
    <div className="min-h-screen bg-background text-foreground flex justify-center">
      <div className="w-full max-w-[720px] px-6 py-12">
        <Link to="/" className="text-[12px] uppercase tracking-[0.22em] text-gold/90">
          ← Project Future
        </Link>

        <h1 className="font-display text-[34px] leading-tight mt-6">Privacy Policy</h1>
        <p className="text-[13px] text-muted-foreground mt-2">Last updated: 2026</p>

        <div className="mt-8 space-y-6 text-[15px] leading-relaxed text-foreground/90">
          <p>
            Project Future ("the app", "we") is a simulation-only intentional-spending app.
            This policy explains what data the app handles.
          </p>

          <Section title="The short version">
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                We do <strong>not</strong> process payments, connect to your bank, or collect any
                card, UPI, or financial-account information. Ever.
              </li>
              <li>
                The app is a simulation: brands and listings are fictional, and your "savings" are a
                personal tally of purchases you chose not to make.
              </li>
              <li>We do not sell or share your data with third parties.</li>
              <li>We do not show ads.</li>
            </ul>
          </Section>

          <Section title="What we collect">
            <p>
              To let you use the app without creating an account, we generate a random{" "}
              <strong>guest device identifier</strong> and store the data you create against it:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 mt-3">
              <li>
                <strong>Your goals / dreams</strong> — titles, target amounts, dates, and progress
                you enter.
              </li>
              <li>
                <strong>Your intentional-choice activity</strong> — the tally of cravings you chose
                to skip and which goal you directed them toward.
              </li>
              <li>
                <strong>A guest device identifier</strong> — a random id generated by the app (not
                your device's hardware or advertising identifier) so your data syncs to you without
                a login.
              </li>
            </ul>
            <p className="mt-3">
              We do <strong>not</strong> collect: your name (unless you type it into a goal),
              contacts, location, photos, messages, real financial or payment information, or any
              device advertising identifier.
            </p>
          </Section>

          <Section title="How we use it">
            <p>
              Solely to provide the app's core function — saving and syncing your own dreams and
              progress across sessions. We do not use your data for advertising or profiling, and we
              do not share it with third parties.
            </p>
          </Section>

          <Section title="Data security">
            <p>
              Data is transmitted over encrypted connections (HTTPS/TLS) and stored on our backend
              infrastructure.
            </p>
          </Section>

          <Section title="Data retention & deletion">
            <p>
              Your data is retained while your guest profile is active. To request deletion of your
              data, contact us at the email below and we will remove the data associated with your
              guest identifier.
            </p>
          </Section>

          <Section title="Children">
            <p>
              The app is not directed at children under 13 and does not knowingly collect data from
              them.
            </p>
          </Section>

          <Section title="Changes">
            <p>
              We may update this policy; material changes will be reflected here with a new "last
              updated" date.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              For privacy questions or data-deletion requests:{" "}
              <span className="text-gold">hello@projectfuture.app</span>
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-display text-[20px] text-foreground mb-2">{title}</h2>
      {children}
    </section>
  );
}

export default Privacy;
