// AUTO-GENERATED by scripts/fetch-pexels.mjs (or hand-edited for local files).
// Maps productId -> ProductMedia for real photographs. Empty until a photo
// source is run/provided. Merged into PHOTO_REGISTRY in productImages.ts.
import type { ProductMedia } from "./productImages";

export const GENERATED_PHOTOS: Record<string, ProductMedia> = {};
